/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import config.Sesion;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class FrmMenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuAdmin
     */
    public FrmMenuAdmin() {
        initComponents();
        this.setResizable(false);
        this.setTitle("Sistema de Facturacion e Inventario de Ferretería");
        this.setSize(new Dimension(900, 500));
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        menuItemNuevoCliente = new javax.swing.JMenuItem();
        menuItemEditarCliente = new javax.swing.JMenuItem();
        menuItemEliminarCliente = new javax.swing.JMenuItem();
        menuItemConsultarCliente = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuItemNuevoEmpleado = new javax.swing.JMenuItem();
        menuItemEditarEmpleado = new javax.swing.JMenuItem();
        menuItemEliminarEmpleado = new javax.swing.JMenuItem();
        menuItemConsultarEmpleado = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuItemNuevoProveedor = new javax.swing.JMenuItem();
        menuItemEditarProveedor = new javax.swing.JMenuItem();
        menuItemEliminarProveedor = new javax.swing.JMenuItem();
        menuItemConsultarProveedor = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuItemNuevoProducto = new javax.swing.JMenuItem();
        menuItemEditarProducto = new javax.swing.JMenuItem();
        menuItemEliminarProducto = new javax.swing.JMenuItem();
        menuItemGestionarProducto1 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        menuItemGestionarCategoria = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemNuevaVenta1 = new javax.swing.JMenuItem();
        menuItemEliminarVenta = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuItemCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        content.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(jLabel1)
                .addContainerGap(356, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel1)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jMenu5.setText("Cliente");
        jMenu5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenu5.setPreferredSize(new java.awt.Dimension(130, 50));

        menuItemNuevoCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuItemNuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-usuario.png"))); // NOI18N
        menuItemNuevoCliente.setText("Nuevo");
        menuItemNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNuevoClienteActionPerformed(evt);
            }
        });
        jMenu5.add(menuItemNuevoCliente);

        menuItemEditarCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuItemEditarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar-usuario.png"))); // NOI18N
        menuItemEditarCliente.setText("Editar");
        menuItemEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEditarClienteActionPerformed(evt);
            }
        });
        jMenu5.add(menuItemEditarCliente);

        menuItemEliminarCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuItemEliminarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar-usuario.png"))); // NOI18N
        menuItemEliminarCliente.setText("Eliminar");
        menuItemEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEliminarClienteActionPerformed(evt);
            }
        });
        jMenu5.add(menuItemEliminarCliente);

        menuItemConsultarCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuItemConsultarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        menuItemConsultarCliente.setText("Consultar");
        menuItemConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsultarClienteActionPerformed(evt);
            }
        });
        jMenu5.add(menuItemConsultarCliente);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/empleado.png"))); // NOI18N
        jMenu6.setText("Empleado");
        jMenu6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenu6.setPreferredSize(new java.awt.Dimension(150, 50));

        menuItemNuevoEmpleado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuItemNuevoEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-usuario.png"))); // NOI18N
        menuItemNuevoEmpleado.setText("Nuevo");
        menuItemNuevoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNuevoEmpleadoActionPerformed(evt);
            }
        });
        jMenu6.add(menuItemNuevoEmpleado);

        menuItemEditarEmpleado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuItemEditarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar-usuario.png"))); // NOI18N
        menuItemEditarEmpleado.setText("Editar");
        menuItemEditarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEditarEmpleadoActionPerformed(evt);
            }
        });
        jMenu6.add(menuItemEditarEmpleado);

        menuItemEliminarEmpleado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuItemEliminarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar-usuario.png"))); // NOI18N
        menuItemEliminarEmpleado.setText("Eliminar");
        menuItemEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEliminarEmpleadoActionPerformed(evt);
            }
        });
        jMenu6.add(menuItemEliminarEmpleado);

        menuItemConsultarEmpleado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuItemConsultarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        menuItemConsultarEmpleado.setText("Consultar");
        menuItemConsultarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsultarEmpleadoActionPerformed(evt);
            }
        });
        jMenu6.add(menuItemConsultarEmpleado);

        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/proveedor.png"))); // NOI18N
        jMenu7.setText("Proveedor");
        jMenu7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenu7.setPreferredSize(new java.awt.Dimension(150, 50));

        menuItemNuevoProveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuItemNuevoProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-usuario.png"))); // NOI18N
        menuItemNuevoProveedor.setText("Nuevo");
        menuItemNuevoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNuevoProveedorActionPerformed(evt);
            }
        });
        jMenu7.add(menuItemNuevoProveedor);

        menuItemEditarProveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuItemEditarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar-usuario.png"))); // NOI18N
        menuItemEditarProveedor.setText("Editar");
        menuItemEditarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEditarProveedorActionPerformed(evt);
            }
        });
        jMenu7.add(menuItemEditarProveedor);

        menuItemEliminarProveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuItemEliminarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar-usuario.png"))); // NOI18N
        menuItemEliminarProveedor.setText("Eliminar");
        menuItemEliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEliminarProveedorActionPerformed(evt);
            }
        });
        jMenu7.add(menuItemEliminarProveedor);

        menuItemConsultarProveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuItemConsultarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        menuItemConsultarProveedor.setText("Consultar");
        menuItemConsultarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsultarProveedorActionPerformed(evt);
            }
        });
        jMenu7.add(menuItemConsultarProveedor);

        jMenuBar1.add(jMenu7);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.png"))); // NOI18N
        jMenu3.setText("Producto");
        jMenu3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenu3.setPreferredSize(new java.awt.Dimension(150, 50));

        menuItemNuevoProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuItemNuevoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar-producto.png"))); // NOI18N
        menuItemNuevoProducto.setText("Nuevo");
        menuItemNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNuevoProductoActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemNuevoProducto);

        menuItemEditarProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuItemEditarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar-producto.png"))); // NOI18N
        menuItemEditarProducto.setText("Editar");
        menuItemEditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEditarProductoActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemEditarProducto);

        menuItemEliminarProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuItemEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar-producto.png"))); // NOI18N
        menuItemEliminarProducto.setText("Eliminar");
        menuItemEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEliminarProductoActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemEliminarProducto);

        menuItemGestionarProducto1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuItemGestionarProducto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        menuItemGestionarProducto1.setText("Consultar");
        menuItemGestionarProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGestionarProducto1ActionPerformed(evt);
            }
        });
        jMenu3.add(menuItemGestionarProducto1);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrito.png"))); // NOI18N
        jMenu8.setText("Categoria");
        jMenu8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenu8.setPreferredSize(new java.awt.Dimension(150, 50));

        menuItemGestionarCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuItemGestionarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        menuItemGestionarCategoria.setText("Gestionar");
        menuItemGestionarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGestionarCategoriaActionPerformed(evt);
            }
        });
        jMenu8.add(menuItemGestionarCategoria);

        jMenu3.add(jMenu8);

        jMenuBar1.add(jMenu3);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrito.png"))); // NOI18N
        jMenu2.setText("Venta");
        jMenu2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(130, 50));

        menuItemNuevaVenta1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuItemNuevaVenta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        menuItemNuevaVenta1.setText("Consultar");
        menuItemNuevaVenta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNuevaVenta1ActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemNuevaVenta1);

        menuItemEliminarVenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuItemEliminarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar-venta.png"))); // NOI18N
        menuItemEliminarVenta.setText("Eliminar");
        menuItemEliminarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEliminarVentaActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemEliminarVenta);

        jMenuBar1.add(jMenu2);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        jMenu4.setText("Cerrar Sesión");
        jMenu4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenu4.setPreferredSize(new java.awt.Dimension(150, 50));

        menuItemCerrarSesion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuItemCerrarSesion.setText("Cerrar Sesión");
        menuItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCerrarSesionActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemCerrarSesion);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemGestionarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGestionarCategoriaActionPerformed
        content.removeAll();
        JPanelCategoria categoria = new JPanelCategoria();
        ShowPanel(categoria);
    }//GEN-LAST:event_menuItemGestionarCategoriaActionPerformed

    private void menuItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCerrarSesionActionPerformed
        this.cerrarSesion();
    }//GEN-LAST:event_menuItemCerrarSesionActionPerformed

    private void menuItemNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNuevoProductoActionPerformed
        content.removeAll();
        JPanelProductoNuevo producto = new JPanelProductoNuevo();
        ShowPanel(producto);
    }//GEN-LAST:event_menuItemNuevoProductoActionPerformed

    private void menuItemGestionarProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGestionarProducto1ActionPerformed
        content.removeAll();
        JPanelConsultarProducto producto = new JPanelConsultarProducto();
        ShowPanel(producto);
    }//GEN-LAST:event_menuItemGestionarProducto1ActionPerformed

    private void menuItemNuevoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNuevoEmpleadoActionPerformed
        content.removeAll();
        JPanelEmpleadoNuevo empleado = new JPanelEmpleadoNuevo();
        ShowPanel(empleado);
    }//GEN-LAST:event_menuItemNuevoEmpleadoActionPerformed

    private void menuItemConsultarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultarEmpleadoActionPerformed
        content.removeAll();
        JPanelConsultarEmpleado empleado = new JPanelConsultarEmpleado();
        ShowPanel(empleado);
    }//GEN-LAST:event_menuItemConsultarEmpleadoActionPerformed

    private void menuItemNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNuevoClienteActionPerformed
        content.removeAll();
        JPanelClienteNuevo cliente = new JPanelClienteNuevo();
        ShowPanel(cliente);
    }//GEN-LAST:event_menuItemNuevoClienteActionPerformed

    private void menuItemConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultarClienteActionPerformed
        content.removeAll();
        JPanelConsultarCliente cliente = new JPanelConsultarCliente();
        ShowPanel(cliente);
    }//GEN-LAST:event_menuItemConsultarClienteActionPerformed

    private void menuItemConsultarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultarProveedorActionPerformed
        content.removeAll();
        JPanelConsultarProveedor proveedor = new JPanelConsultarProveedor();
        ShowPanel(proveedor);
    }//GEN-LAST:event_menuItemConsultarProveedorActionPerformed

    private void menuItemNuevaVenta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNuevaVenta1ActionPerformed
        content.removeAll();
        JPanelConsultarVenta venta = new JPanelConsultarVenta();
        ShowPanel(venta);
    }//GEN-LAST:event_menuItemNuevaVenta1ActionPerformed

    private void menuItemEliminarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEliminarVentaActionPerformed
        content.removeAll();
        JPanelEliminarVenta venta = new JPanelEliminarVenta();
        ShowPanel(venta);
    }//GEN-LAST:event_menuItemEliminarVentaActionPerformed

    private void menuItemNuevoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNuevoProveedorActionPerformed
        content.removeAll();
        JPanelProveedorNuevo proveedor = new JPanelProveedorNuevo();
        ShowPanel(proveedor);
    }//GEN-LAST:event_menuItemNuevoProveedorActionPerformed

    private void menuItemEditarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEditarProveedorActionPerformed
        content.removeAll();
        JPanelProveedorEditar proveedor = new JPanelProveedorEditar();
        ShowPanel(proveedor);
    }//GEN-LAST:event_menuItemEditarProveedorActionPerformed

    private void menuItemEliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEliminarProveedorActionPerformed
        content.removeAll();
        JPanelProveedorEliminar proveedor = new JPanelProveedorEliminar();
        ShowPanel(proveedor);
    }//GEN-LAST:event_menuItemEliminarProveedorActionPerformed

    private void menuItemEditarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEditarEmpleadoActionPerformed
        content.removeAll();
        JPanelEmpleadoEditar empleado = new JPanelEmpleadoEditar();
        ShowPanel(empleado);
    }//GEN-LAST:event_menuItemEditarEmpleadoActionPerformed

    private void menuItemEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEliminarEmpleadoActionPerformed
        content.removeAll();
        JPanelEmpleadoEliminar empleado = new JPanelEmpleadoEliminar();
        ShowPanel(empleado);
    }//GEN-LAST:event_menuItemEliminarEmpleadoActionPerformed

    private void menuItemEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEditarClienteActionPerformed
        content.removeAll();
        JPanelClienteEditar cliente = new JPanelClienteEditar();
        ShowPanel(cliente);
    }//GEN-LAST:event_menuItemEditarClienteActionPerformed

    private void menuItemEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEliminarClienteActionPerformed
        content.removeAll();
        JPanelClienteEliminar cliente = new JPanelClienteEliminar();
        ShowPanel(cliente);
    }//GEN-LAST:event_menuItemEliminarClienteActionPerformed

    private void menuItemEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEditarProductoActionPerformed
        content.removeAll();
        JPanelProductoEditar producto = new JPanelProductoEditar();
        ShowPanel(producto);
    }//GEN-LAST:event_menuItemEditarProductoActionPerformed

    private void menuItemEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEliminarProductoActionPerformed
        content.removeAll();
        JPanelProductoEliminar producto = new JPanelProductoEliminar();
        ShowPanel(producto);
    }//GEN-LAST:event_menuItemEliminarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuItemCerrarSesion;
    private javax.swing.JMenuItem menuItemConsultarCliente;
    private javax.swing.JMenuItem menuItemConsultarEmpleado;
    private javax.swing.JMenuItem menuItemConsultarProveedor;
    private javax.swing.JMenuItem menuItemEditarCliente;
    private javax.swing.JMenuItem menuItemEditarEmpleado;
    private javax.swing.JMenuItem menuItemEditarProducto;
    private javax.swing.JMenuItem menuItemEditarProveedor;
    private javax.swing.JMenuItem menuItemEliminarCliente;
    private javax.swing.JMenuItem menuItemEliminarEmpleado;
    private javax.swing.JMenuItem menuItemEliminarProducto;
    private javax.swing.JMenuItem menuItemEliminarProveedor;
    private javax.swing.JMenuItem menuItemEliminarVenta;
    private javax.swing.JMenuItem menuItemGestionarCategoria;
    private javax.swing.JMenuItem menuItemGestionarProducto1;
    private javax.swing.JMenuItem menuItemNuevaVenta1;
    private javax.swing.JMenuItem menuItemNuevoCliente;
    private javax.swing.JMenuItem menuItemNuevoEmpleado;
    private javax.swing.JMenuItem menuItemNuevoProducto;
    private javax.swing.JMenuItem menuItemNuevoProveedor;
    // End of variables declaration//GEN-END:variables

    private void cerrarSesion() {
        int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que quieres cerrar sesión?", "Cerrar Sesión", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            Sesion.cerrarSesion(); 

            this.dispose();

            FrmLogin loginFrame = new FrmLogin();
            loginFrame.setVisible(true);
        }
    }
    private void ShowPanel(JPanel p) {
        p.setSize(900, 400);
        p.setLocation(0, 0);
        
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

    }
}
