/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.EmpleadoController;
import controlador.UsuarioController;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author admin
 */
public class JPanelEmpleadoEliminar extends javax.swing.JPanel {

    private int idEmpleado;
    private int idUsuario;
    private EmpleadoController empleadoController;
    private UsuarioController usuarioController;

    /**
     * Creates new form JPanelCategoriaNuevo
     */
    public JPanelEmpleadoEliminar() {
        initComponents();
        this.setSize(new Dimension(900, 400));
        empleadoController = new EmpleadoController();
        usuarioController = new UsuarioController();
        this.cargarEmpleadosEnTabla();txtBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent e) {
                String texto = txtBuscador.getText().trim();
                if (texto.isEmpty()) {
                    cargarEmpleadosEnTabla();
                }
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnActivar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableEmpleado = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtBuscador = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Eliminar Empleados");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        btnActivar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnActivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/activar.png"))); // NOI18N
        btnActivar.setText("Activar");
        btnActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarActionPerformed(evt);
            }
        });
        add(btnActivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 140, 30));

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/desactivar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 140, 30));

        jScrollPane4.setPreferredSize(new java.awt.Dimension(450, 80));

        tableEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cedula", "Nombre", "Apellido", "Telefono", "Dirección", "Correo", "usuario", "Contraseña", "Rol", "Estado", "idUsuario"
            }
        ));
        jScrollPane4.setViewportView(tableEmpleado);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 860, 240));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        jLabel8.setText("Buscar:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 30));

        txtBuscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscadorKeyPressed(evt);
            }
        });
        add(txtBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 670, -1));

        btnBuscar.setBackground(new java.awt.Color(204, 204, 255));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 70, 90, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarActionPerformed
        this.activar();
    }//GEN-LAST:event_btnActivarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tableEmpleado.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un empleado para desactivar");
            return;
        }
        idEmpleado = Integer.parseInt(tableEmpleado.getValueAt(fila, 0).toString());
        idUsuario = Integer.parseInt(tableEmpleado.getValueAt(fila, 11).toString());

        String mensaje = empleadoController.desactivarEmpleado(idEmpleado);
        usuarioController.desactivarUsuario(idUsuario);

        JOptionPane.showMessageDialog(null, mensaje);
        this.cargarEmpleadosEnTabla();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtBuscadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            this.buscarEmpleados();
        }
    }//GEN-LAST:event_txtBuscadorKeyPressed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        this.buscarEmpleados();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void buscarEmpleados() {
        String criterio = txtBuscador.getText().trim();
        if (criterio.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese un criterio de búsqueda");
            cargarEmpleadosEnTabla();
            return;
        }

        List<Object[]> resultados = empleadoController.buscarEmpleados(criterio);
        DefaultTableModel model = (DefaultTableModel) tableEmpleado.getModel();
        model.setRowCount(0);

        for (Object[] fila : resultados) {
            model.addRow(fila);
        }

        if (resultados.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se encontraron resultados.");
            cargarEmpleadosEnTabla();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTable tableEmpleado;
    private javax.swing.JTextField txtBuscador;
    // End of variables declaration//GEN-END:variables
    private void cargarEmpleadosEnTabla() {
        DefaultTableModel model = (DefaultTableModel) tableEmpleado.getModel();
        model.setRowCount(0);

        EmpleadoController controller = new EmpleadoController();
        List<Object[]> empleadosConUsuario = controller.obtenerEmpleados();

        for (Object[] fila : empleadosConUsuario) {
            model.addRow(fila);
        }

        tableEmpleado.setModel(model);
        if (model.getColumnCount() > 11) {
            tableEmpleado.getColumnModel().getColumn(11).setMinWidth(0);
            tableEmpleado.getColumnModel().getColumn(11).setMaxWidth(0);
            tableEmpleado.getColumnModel().getColumn(11).setWidth(0);
        }

        if (empleadosConUsuario.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No existen empleados registrados actualmente.");
        }
    }

    private void activar() {
        int fila = tableEmpleado.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un producto para activar");
            return;
        }
        idEmpleado = Integer.parseInt(tableEmpleado.getValueAt(fila, 0).toString());
        idUsuario = Integer.parseInt(tableEmpleado.getValueAt(fila, 11).toString());

        String mensaje = empleadoController.activarEmpleado(idEmpleado);
        usuarioController.activarUsuario(idUsuario);

        JOptionPane.showMessageDialog(null, mensaje);
        this.cargarEmpleadosEnTabla();
    }
}
